/**
 * @file main.c
 * @author Trương Quốc Ánh (you@domain.com)
 * @brief Take data from BME280 and saved into SD card
 * @version 0.1
 * @date 2023-12-28
 * 
 * @copyright Copyright (c) 2023
 * 
 */
#include <esp_system.h>
#include <nvs_flash.h>
#include <stdio.h>
#include <string.h>

#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "driver/sdmmc_host.h"
#include "driver/sdmmc_defs.h"
#include "sdmmc_cmd.h"
#include "esp_vfs_fat.h"
#include "sdkconfig.h"  /** Generated by "make menuconfig" */

#include "bme.h"


#define SDA_PIN 21                     /** SDA pin: 21 */
#define SCL_PIN 22                     /** SCL pin: 22 */



static esp_err_t init_sd_card (void)
{
    /**
     * @brief Default sdmmc_host_t structure initializer for SDMMC peripheral Uses SDMMC peripheral, with 4-bit mode enabled, and max frequency set to 20MHz
     * @note This variable identify communication's settings to SD Card
     */
    sdmmc_host_t host = SDMMC_HOST_DEFAULT();
    sdmmc_slot_config_t slot_config = SDMMC_SLOT_CONFIG_DEFAULT(); /** Macro defining default configuration of SDMMC host slot */
    /** this code line use to config stucture of Mount (gắn kết) file system FAT's process */
    esp_vfs_fat_sdmmc_mount_config_t mount_config =
    {
        .format_if_mount_failed = false, /** Do not reformat  SD card whenever having problem in mount processing */
        .max_files = 3, /** Max number of opened files in the same time */
    };
    sdmmc_card_t *card;
    /**
     * @brief After config the structure of FAT in code line upper, this line will initialize and mount FAT file
     * @param 1: Link where we want to mount file FAT into
     * @param 2: pointer of "sdmmc_host_t" configured. This variable identify communication's settings to SD Card
     * @param 3: pointer of "sdmmc_slot_config_t" configured. This variable contains settings related to the SD Card slot
     * @param 4: pointer of "sdmmc_card_t". When this function succeed, the data of this function will be saved in this variable.
     */
    esp_err_t err = esp_vfs_fat_sdmmc_mount("/SD card", &host, &slot_config, &slot_config, &card);
    if (err != ESP_OK)
    {
        return err;
    }
    return ESP_OK;
}


static void save_inf(void *arg)
{
    
    char str[100];
    sprintf(str, "temperature = %.2f, humidity = %.2f, pressure = %.2f ", my_data.temperature, my_data.humidity, my_data.pressure);
    FILE *file = fopen("data.text", "w");
    if (file == NULL)
    {
        printf(" err: fopen failed\n");
    }
    else 
    {
        fwrite(str, 1, sizeof(str), file);
        fclose(file);
    }
    vTaskDelete(NULL);
    printf(" Finished Save Information\n");
}



/** Execution function when interrupt occur   */
static void save_data (void *arg)
{
    
    xTaskCreate(save_inf, "Save infor", 1024, NULL, 15, NULL);
    vTaskDelay(10000/portTICK_PERIOD_MS); /**delay 10s */

}




void app_main()
{
    esp_err_t err = init_sd_card();
    if (err != ESP_OK)
        {
            printf(" err: %s", esp_err_to_name(err));
            return;
        }
    /**
     * @brief Value return of the init faction is the error code of gpio_isr_handler_add. If we add ISR handler to Button Pin successfully, we will skip 
     * this code
     * 
     */
    if (err != ESP_OK)
    {
        printf("err: %s\n", esp_err_to_name(err));
        return;
    }
    i2c_master_bme_init(SDA_PIN, SCL_PIN);
    // xTaskCreate(&bme280_reader_task, "bme_280_reader_task", (1024 *2), NULL, 6, NULL);
    // xTaskCreate(&save_data, "save_data", (1024 *2), NULL,10, NULL);
}